tolls
Shift3/DevOps-Apprenticeship-Notes pull request #43
Opened 2023-02-02 21:54 UTC by tiruworktito

**When you open your pull requests, remove the lines that start and end with underscores (\_)**

## Changes
_List Changes Introduced by this PR_
1. Item 1
2. Item 2

## Purpose
_Describe the problem or feature in addition to a link to the issues._

## Approach
_How does this change address the problem?_

## Pre-Testing TODOs
_What needs to be done before testing_
- [] Change database values in x collection to y.

## Testing Steps
_How do the users test this change?_

## Learning
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

_If this closes an issue, name it here. If it doesn't, remove this line_
Closes #000

2023-02-03 04:55 UTC, fedluk70 reviewed
checked

2023-02-08 22:03 UTC, michaelachrisco requested changes
PR looks great @tiruworktito ! I added a couple of changes that I think should be added before this gets merged, just adding descriptions to the links themselves. Awesome job on the PR description as well.

2023-02-08 22:03 UTC, michaelachrisco commented on README.md
> +* https://www.youtube.com/watch?v=SLB_c_ayRMo
Lets add a description with a note on why this video is important for others to take a look at. That will help everyone else out.

2023-02-08 22:03 UTC, michaelachrisco commented on README.md
> +* tools  https://docs.docker.com/engine/install/linux-postinstall/
Lets add what kind of tools we are looking at here. The link is great! Docker docs are a very good resource. Did you use any specific tool set within the docs?

2023-02-09 05:36 UTC, closed without merging