Resolving merge conflict
Shift3/DevOps-Apprenticeship-Notes pull request #68
Opened 2023-02-09 08:54 UTC by demewozshiferaw

## Changes
Added a step to take when merge conflict happen 

## Purpose
Resolve with merge conflict 

## Testing Steps
link not 404

## Learning
N/A

Closes #6

2023-02-14 00:10 UTC, fedluk70 reviewed
Looks cool

2023-04-05 16:57 UTC, michaelachrisco requested changes
Thanks for adding so many new resources! Thanks for the contribution!

In order to resolve the merge conflict, my suggestion would be to close this PR at this time and remake the branch from scratch. Sometimes its just easier to do that then go over the many many merge conflicts. Let me know if you need help with that.

2023-04-05 16:57 UTC, michaelachrisco commented on README.md
> +practicing
Lets remove the branch names and "test" or "practicing" messages within the documentation.

2023-04-05 16:57 UTC, michaelachrisco commented on README.md
> + development
Same here, lets remove this.

2023-04-05 16:57 UTC, michaelachrisco commented on README.md
> +### https://youtu.be/kqtD5dpn9C8
Why is this link turned into a header? My suggestion would be to remove the header. Like so: 
```suggestion
https://youtu.be/kqtD5dpn9C8
```

2023-04-05 16:57 UTC, michaelachrisco commented on README.md
> + HEAD
Lets remove the HEAD line. Please refer to the merge conflict talk that we had if you are confused on how to do this.

2023-04-05 16:57 UTC, michaelachrisco commented on README.md
> +- [resolving-a-merge-conflict-using-the-command-line](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command
Nice link!

2023-04-05 16:57 UTC, michaelachrisco commented on README.md
> +
Im thinking you may want to rework this change.

2023-04-05 16:57 UTC, michaelachrisco commented on README.md
> +development
Lets remove the branch names like stated above.

2023-05-01 20:04 UTC, michaelachrisco commented
Closing all old Prs over 1 month old. Feel free to re-submit!

2023-05-01 20:04 UTC, closed without merging